#!/usr/bin/env groovy

node {
	try {
		cleanWs()

		stage('Checkout') {
			checkout scm
		}

		stage('Build and Test') {
			withMaven(maven: 'M3',
			          jdk: 'J8',
			          mavenLocalRepo: '.repository',
			          options: [artifactsPublisher(disabled: true),
			                    openTasksPublisher(disabled: true)]) {

				// Build and run tests
				sh "mvn clean test"
			}

			// Coverage reports
			jacoco(execPattern: 'target/jacoco.exec',
			       classPattern: 'target/classes/org/electronicvisions',
			       changeBuildStatus: true,
			       maximumLineCoverage: '100')
		}
	} catch (Exception e) {
		post_error_build_action()
		throw e
	} finally {
		post_all_build_action()
	}

	// Some Jenkins steps fail a build without raising (e.g. archiveArtifacts)
	if (currentBuild.currentResult != "SUCCESS") {
		post_error_build_action()
	}
}

/*
/* HELPER FUNCTIONS
*/

void post_all_build_action() {
	// Always clean the workspace
	cleanWs()
}

void post_error_build_action() {
	notifyFailure(mattermostChannel: "#softies")
}
